### ISSUE TITLE
Simplify proofs using the no-mobility lemmas

### ISSUE THREAD

**Issue by jeltsch** [input-output-hk/thorn-calculus#72]
The no-mobility versions of transition system rules introduced by #71 should allow us to simplify several proofs in the Þ-calculus implementation. We shall identify all places where such a simplification is possible and perform it there.

**Comment by jeltsch** [comment]
Hmm, I scanned the theories `Thorn_Calculus-Semantics-Synchronous` and `Thorn_Calculus-Core_Bisimilarities` (in particular, I searched for occurrences of `0`), but I couldn’t find places where the no-mobility lemmas would be useful. Do you know any such places? If not, I’ll close this issue with *reason: invalid*.

**Comment by javierdiaz72** [comment]
> Hmm, I scanned the theories `Thorn_Calculus-Semantics-Synchronous` and `Thorn_Calculus-Core_Bisimilarities` (in particular, I searched for occurrences of `0`), but I couldn’t find places where the no-mobility lemmas would be useful. @javierdiaz72, do you know any such places? If not, I’ll close this issue with _reason: invalid_.

No, I'm not aware of opportunities of use for the no-mobility lemmas here, so I think we should close this issue.
